
server:
  port: 8080

#spring:
#    datasource:
#       name: test
#       url: jdbc:mysql://127.0.0.1:3306/agent
#       username: root
#       password:
#       driver-class-name: com.mysql.jdbc.Driver

 #数据库链接设置
spring:
  datasource:
    name: druid
    druidClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agent?characterEncoding=utf-8&useSSL=false
    username: root
    password:
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小，最小，最大
    initialSize: 10
    minIdle: 10
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久进行一次检测，检测需要关闭空闲的连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize : 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall, logback
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.bdcom.entity  # 注意：对应实体类的路径